version: "<%= configVersion %>"
services:
  <%= serviceName %>:
<% if (imageName) { -%>
    image: <%= imageName %>
<% } else { %>
    build:
      context: .
      dockerfile: Dockerfile
      args: {}
<% } %>
